import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Project",
  description: "Generated by Sude Dalyan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" href="https://i.ibb.co/x1GkmH1/logo.png" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
